### ISSUE TITLE
Created or channel clips?

### ISSUE THREAD

**Issue by Naniad** [danefairbanks/TwitchClipManager#1]
Does this work for clips I've created or only for clips of my channel? I would love it to work for clips I've created if not.

**Comment by EchebKeso** [comment]
I've just created a PR that does this, tested on my own clips (hundreds more than my own channel 😂

**Comment by Naniad** [comment]
Thanks! Shame I do not have the knowledge to add it myself so hopefully it will get added soon.

**Comment by danefairbanks** [comment]
latest version handles this
