### ISSUE TITLE
Application exiting after deletion

### ISSUE THREAD

**Issue by AcidzDev** [danefairbanks/TwitchClipManager#4]
Hi, Had a couple of friends contact me about this program. Issue of the application exiting after deletion

Quick read over the code

``if (options.Delete && deleteClips.Count > 10)
                {
                    Console.WriteLine($"Deleting {string.Join(',', deleteClips)}");
                    DeleteClips(deleteClips);
                    deleteClips.Clear();
                }
                if (clips.Count < 900) break;
            } while (options.Delete && !quit);
        } ``

Possible remove the && !quit to be causing the issue.

Tried to test it myself. VS failed to build.

Any testing of this required, happy to help

**Comment by danefairbanks** [comment]
i saw this but i was already in a complete rewrite of silently going over data that gave errors
